import json
import logging
import os

from dotenv import load_dotenv
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_core.runnables import RunnableConfig
from langchain_core.tools import tool
from protollm.connectors import create_llm_connector
from pathlib import Path
from fastmcp import FastMCP

from CoScientist.chemical_utils.chemical_functions import extract_reactions_from_pdf, extract_molecules_from_pdf, remove_keys
from CoScientist.paper_analysis.chroma_db_operations import ChromaDBPaperStore
from CoScientist.paper_analysis.prompts import paraphrase_prompt
from CoScientist.paper_analysis.question_processing import process_question, simple_query_llm

ENV_PATH = Path(__file__).resolve().parents[1] / ".env"
load_dotenv(ENV_PATH)

VISION_LLM_URL = os.environ["VISION_LLM_URL"]

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

mcp = FastMCP("PaperAnalysis")

@mcp.tool()
def explore_chemistry_database(task: str) -> dict:
    """
    Leverages a database of chemical scientific papers to answer user questions.
    This tool is prioritized over web searches for information.
    It is designed for general inquiries and not for details specific to individual papers
    (e.g., figure descriptions, experimental details, conclusions) or for identifying
    lists of relevant publications.
    
    Args:
        task (str): The user's question or query related to chemistry.
    
    Returns:
        dict: A dictionary containing the LLM's response, the supporting
            text, images, and tables extracted from the database, and metadata
            about the request (model used, token count, etc.).
    """
    try:
        logger.info('Running explore_chemistry_database tool...')
        logger.info(f'task: {task}')
        paper_store = ChromaDBPaperStore()
        return process_question(task, paper_store)
    except Exception as e:
        logger.error(f'explore_chemistry_database ERROR: {e}')
        return {'answer': 'Could not extract any data from DB.'}


@mcp.tool()
def explore_my_papers(task: str, config: RunnableConfig) -> dict:
    """
    Answers questions based on the content of user-provided scientific papers. 
    This tool allows users to query specific documents they've uploaded, retrieving insights 
    like figure descriptions, experimental details, or conclusions. It prioritizes answers
    from these papers over general web searches.
    It can also answer questions concerning the document set itself (e.g., number of uploaded papers,
    their presence, titles, authors, or other metadata).
    
    Args:
        task (str): The user's question about the uploaded papers.

    Returns:
        dict: A dictionary containing the answer generated by the LLM and metadata 
              about the request (e.g., model used, token count).  
              Returns an error message if no papers are provided or if data extraction fails.
    """
    logger.info('Running explore_my_papers tool...')
    logger.info(f'task: {task}')

    session_id = config.get("configurable", {}).get("session_id", "1")

    directory = Path(os.environ.get('MY_PAPERS_PATH'))
    papers = [str(f.resolve()) for f in directory.iterdir() if f.is_file() and f.suffix.lower() == '.pdf']

    if not papers:
        return {'answer': 'No papers provided for search.'}
    
    logger.info(f'PAPERS from explore_my_papers: {papers}')

    logger.info(f'Requesting PDF image description from server...')
    img_descriptions = 'This is additional information about the reactions and molecules that are presented' \
                    'on the images in the paper. They are passed in the same order as papers themselves.' \
                    'Use them to answer the question.\n\n'
    for paper in papers:
        with open(paper, 'rb') as paper_bytes:
            detected_reactions = remove_keys(extract_reactions_from_pdf(paper_bytes))
            img_descriptions += f'Reactions: {str(detected_reactions)}\n'
        with open(paper, 'rb') as paper_bytes:
            detected_molecules = remove_keys(extract_molecules_from_pdf(paper_bytes))
            img_descriptions += f'Molecules: {str(detected_molecules)}\n'
        img_descriptions += '\n\n'

    try:
        return simple_query_llm(VISION_LLM_URL, task, papers, img_descriptions)
    except Exception as e:
        logger.error(f'explore_my_papers ERROR: {e}')
        return {'answer': 'Could not extract any data from uploaded papers.'}


if __name__ == "__main__":
    mcp.run(transport="http", host="0.0.0.0", port=7331, path="/mcp")
