import logging
import os

from langchain_core.runnables import RunnableConfig
from langchain_core.tools import tool
from fastmcp import FastMCP
from io import BytesIO


class NamedBytesIO(BytesIO):
    def __init__(self, data: bytes, name: str = "document.pdf"):
        super().__init__(data)
        self.name = name
from urllib.parse import urlparse
from pprint import pprint

from CoScientist.chemical_utils.chemical_functions import extract_reactions_from_pdf, extract_molecules_from_pdf, remove_keys
from CoScientist.paper_analysis.chroma_db_operations import ChromaDBPaperStore
from CoScientist.paper_analysis.question_processing import process_question, simple_query_llm
from CoScientist.paper_parser.s3_connection import S3BucketService
from CoScientist.paper_parser.utils import extract_s3_bucket_and_key

s3_service = S3BucketService(
    endpoint=os.getenv("S3__ENDPOINT_URL"),
    access_key=os.getenv("S3__ACCESS_KEY"),
    secret_key=os.getenv("S3__SECRET_KEY"),
    bucket_name=os.getenv("S3__BUCKET_NAME"),
)

from prompts import explore_my_papers_prompt, sys_prompt

VISION_LLM_URL = os.getenv("LLM__VISION_URL")

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

mcp = FastMCP("PaperAnalysis")

@mcp.tool()
def explore_chemistry_database(task: str) -> dict:
    """
    Leverages a database of chemical scientific papers to answer user questions.
    This tool is prioritized over web searches for information.
    It is designed for general inquiries and not for details specific to individual papers
    (e.g., figure descriptions, experimental details, conclusions) or for identifying
    lists of relevant publications.
    
    Args:
        task (str): The user's question or query related to chemistry.
    
    Returns:
        dict: A dictionary containing the LLM's response, the supporting
            text, images, and tables extracted from the database, and metadata
            about the request (model used, token count, etc.).
    """
    try:
        logger.info('Running explore_chemistry_database tool...')
        logger.info(f'task: {task}')
        paper_store = ChromaDBPaperStore()
        return process_question(task, sys_prompt, paper_store)
    except Exception as e:
        logger.error(f'explore_chemistry_database ERROR: {e}')
        return {'answer': 'Could not extract any data from DB.'}


@mcp.tool()
def explore_my_papers(task: str, s3_keys: list[str]) -> dict:
    """
    Answers questions based on the content of user-provided scientific papers. 
    This tool allows users to query specific documents they've uploaded, retrieving insights 
    like figure descriptions, experimental details, or conclusions. It prioritizes answers
    from these papers over general web searches.
    It can also answer questions concerning the document set itself (e.g., number of uploaded papers,
    their presence, titles, authors, or other metadata).
    
    Args:
        task (str): The user's question about the uploaded papers.
        s3_keys (list[str]): The list of S3 keys for the uploaded papers.
        config (RunnableConfig): The configuration for the runnable.


    Returns:
        dict: A dictionary containing the answer generated by the LLM and metadata 
              about the request (e.g., model used, token count).  
              Returns an error message if no papers are provided or if data extraction fails.
    """
    logger.info('Running explore_my_papers tool...')
    logger.info(f'task: {task}')

    if not s3_keys:
        return {'answer': 'No papers provided for search.'}

    logger.info(f'S3 keys for explore_my_papers: {s3_keys}')

    client = s3_service.create_s3_client()

    try:
        paper_buffers: list[BytesIO] = []
        for s3_key in s3_keys:
            try:
                response = client.get_object(Bucket=s3_service.bucket_name, Key=s3_key)
                paper_buffers.append(BytesIO(response['Body'].read()))
            except client.exceptions.NoSuchKey:
                logger.warning(f"S3 key not found, skipping: {s3_key}")

        if not paper_buffers:
            return {'answer': 'No valid papers could be loaded from S3.'}

        logger.info(f'PAPERS from explore_my_papers: {s3_keys}')

        logger.info(f'Requesting PDF image description from server...')
        img_descriptions = 'This is additional information about the reactions and molecules that are presented' \
                        'on the images in the paper. They are passed in the same order as papers themselves.' \
                        'Use them to answer the question.\n\n'
        for buf in paper_buffers:
            buf.seek(0)
            detected_reactions = remove_keys(extract_reactions_from_pdf(('document.pdf', buf, 'application/pdf')))
            img_descriptions += f'Reactions: {str(detected_reactions)}\n'
            buf.seek(0)
            detected_molecules = remove_keys(extract_molecules_from_pdf(('document.pdf', buf, 'application/pdf')))
            img_descriptions += f'Molecules: {str(detected_molecules)}\n'
            img_descriptions += '\n\n'

        for buf in paper_buffers:
            buf.seek(0)
        return simple_query_llm(VISION_LLM_URL, task, explore_my_papers_prompt, paper_buffers, img_descriptions)
    except Exception as e:
        logger.error(f'explore_my_papers ERROR: {e}')
        return {'answer': 'Could not extract any data from uploaded papers.'}


if __name__ == "__main__":
    mcp.run(transport="http", host="0.0.0.0", port=7331, path="/mcp")
